# Generated by Django 5.1.3 on 2025-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetLink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Username'),
        ),
    ]
