# Generated by Django 5.1.3 on 2025-05-01 19:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetLink', '0002_alter_usuario_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe tener 9 dígitos.', regex='^\\d{9}$')], verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False, verbose_name='Asistencia confirmada')),
                ('asistente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetLink.contacto', verbose_name='Asistente')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fecha de fin')),
                ('transporte', models.CharField(max_length=20, verbose_name='Medio de transporte')),
                ('presupuesto', models.BooleanField(default=False, verbose_name='Presupuesto')),
                ('maleta', models.BooleanField(default=False, verbose_name='Maleta')),
                ('todo', models.BooleanField(default=False, verbose_name='To Do')),
                ('p_alojamiento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('p_transporte', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('p_comida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('p_otros', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe tener 9 dígitos.', regex='^\\d{9}$')], verbose_name='Teléfono')),
                ('asistentes', models.ManyToManyField(blank=True, through='meetLink.Asistencia', to='meetLink.contacto', verbose_name='Asistentes')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='asistencia',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetLink.evento', verbose_name='Evento'),
        ),
        migrations.CreateModel(
            name='EventosUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetLink.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Usuario',
                'verbose_name_plural': 'Eventos de Usuario',
            },
        ),
        migrations.CreateModel(
            name='GrupoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del grupo')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripción del grupo')),
                ('integrantes', models.ManyToManyField(blank=True, to='meetLink.contacto', verbose_name='Integrantes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Grupo de contacto',
                'verbose_name_plural': 'Grupos de contacto',
            },
        ),
    ]
