# Generated by Django 5.1.3 on 2025-05-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetLink', '0004_alter_evento_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
