# Generated by Django 5.1.3 on 2025-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetLink', '0005_delete_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupocontacto',
            name='integrantes',
            field=models.ManyToManyField(blank=True, to='meetLink.contacto', verbose_name='Integrantes (Mantén Ctrl para seleccionar varios)'),
        ),
    ]
